In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from pathlib import Path
from json import loads
import sys, os
import yaml
import shutil

sys.path.append("../")
from reef.plot import stack_images, plot_sample, plot_stack
from reef.ops import coco2yolo

%load_ext autoreload
%autoreload 2

In [3]:
def get_bboxes(annotations):
    bboxes = []
    for annotation in annotations:
        bboxes.append([
            annotation['x'],
            annotation['y'],
            annotation['width'],
            annotation['height']
        ])
    return bboxes

In [4]:
data_dir = Path("../../data/raw")
images_dir = data_dir / "train_images"

In [5]:
df_train = pd.read_csv(data_dir / 'train.csv')
df_train['path'] = 'video_' + df_train.video_id.astype(str) + '/' + df_train.video_frame.astype(str) + '.jpg'
df_train['path'] = df_train.path.map(lambda x: (images_dir / x).resolve().as_posix())
df_train['annotations'] = df_train.annotations.map(lambda x: loads(x.replace("'", '"')))
df_train['bboxes'] = df_train.annotations.apply(get_bboxes)
df_train['n_bboxes'] = df_train.bboxes.apply(len)
df_train

,video_id,sequence,video_frame,sequence_frame,image_id,annotations,path,bboxes,n_bboxes
0,0,40258,0,0,0-0,[],/home/isabella/code/competitions/great_barrier...,[],0
1,0,40258,1,1,0-1,[],/home/isabella/code/competitions/great_barrier...,[],0
2,0,40258,2,2,0-2,[],/home/isabella/code/competitions/great_barrier...,[],0
3,0,40258,3,3,0-3,[],/home/isabella/code/competitions/great_barrier...,[],0
4,0,40258,4,4,0-4,[],/home/isabella/code/competitions/great_barrier...,[],0
...,...,...,...,...,...,...,...,...,...
23496,2,29859,10755,2983,2-10755,[],/home/isabella/code/competitions/great_barrier...,[],0
23497,2,29859,10756,2984,2-10756,[],/home/isabella/code/competitions/great_barrier...,[],0
23498,2,29859,10757,2985,2-10757,[],/home/isabella/code/competitions/great_barrier...,[],0
23499,2,29859,10758,2986,2-10758,[],/home/isabella/code/competitions/great_barrier...,[],0
23500,2,29859,10759,2987,2-10759,[],/home/isabella/code/competitions/great_barrier...,[],0

## Train/val split

In [6]:
import numpy as np


sequence_target_rate = (
    df_train
    .groupby('sequence')
    .agg(
        target_rate = ('annotations', lambda x: np.mean(list(map(len, x))))
    )
    .reset_index()
)

non_zero_sequences = sequence_target_rate.query('target_rate > 0').sequence.tolist()
zero_sequences = sequence_target_rate.query('target_rate == 0').sequence.tolist()

print(f"Number of sequences with nonzero target rate: {len(non_zero_sequences)}")
print(f"Number of sequences with zero target rate: {len(zero_sequences)}")

Number of sequences with nonzero target rate: 17
Number of sequences with zero target rate: 3

In [7]:
from sklearn.model_selection import train_test_split

train_sequences, test_sequences = train_test_split(non_zero_sequences, train_size=13, random_state=42)
zero_train_sequences, zero_test_sequences = train_test_split(zero_sequences, train_size=2, random_state=42)

train_sequences = train_sequences + zero_train_sequences
test_sequences = test_sequences + zero_test_sequences

In [9]:
df_train['split'] = np.where(df_train.sequence.isin(train_sequences), 'train', 'valid')

In [10]:
df_train.groupby("split").agg(
    target_rate = ('annotations', lambda x: np.mean(list(map(len, x))))
)

       target_rate
split
train     0.531850
valid     0.372346

## Data files

### Train/val paths

#### Prepare directory for split

In [76]:
split_name = 's1'  # means small 5% of original dataset

prepared_data_dir = Path(f"../../data/splits/{split_name}")
prepared_data_dir.mkdir(exist_ok=True)

images_splits_dir = prepared_data_dir / "images"

#### Subsample a fraction of original dataset (for dev only)

For each sequence select only a fraction of samples randomly

In [77]:
# group by sequence and sample frac
frac = 0.01
sampled_df = (
    df_train
    .groupby('sequence')
    .sample(frac=frac, random_state=42)
)

# check difference in target rates between original set and sampled
(
    sampled_df
    .groupby('sequence')
    .agg(
        target_rate = ("n_bboxes", lambda x: np.mean(list(map(lambda x: x > 0, x))))
    )
    .sort_index()
).join(
    (
        df_train
        .groupby('sequence')
        .agg(
            target_rate = ("n_bboxes", lambda x: np.mean(list(map(lambda x: x > 0, x))))
        )
        .sort_index()
    ),
    how='left',
    lsuffix="_sampled",
    rsuffix="_original"
)

          target_rate_sampled  target_rate_original
sequence
996                  0.222222              0.226436
8399                 0.214286              0.396346
8503                 0.464286              0.386915
15827                0.000000              0.096104
17665                1.000000              1.000000
18048                1.000000              1.000000
22643                0.416667              0.462340
26651                0.066667              0.019016
29424                0.000000              0.000000
29859                0.033333              0.023762
35305                0.000000              0.093787
37114                0.000000              0.000000
40258                0.800000              0.593750
44160                0.000000              0.000000
45015                0.166667              0.035656
45518                0.375000              0.154135
53708                0.818182              0.653668
59337                0.000000              0.290503
60510                0.250000              0.096829
60754                0.266667              0.221021

##### Check target rate in sampled set

In [78]:
sampled_df.groupby("split").agg(
    target_rate = ('annotations', lambda x: np.mean(list(map(len, x))))
)

       target_rate
split
train     0.696970
valid     0.263158

#### Drop images in train set with no labels to reduce it total fraction in train set to 10%

In [79]:
# index of images in train set with empty bboxes
no_labels_train_idx = sampled_df.query("split == 'train'").query("n_bboxes == 0").index 
print(f"Got {no_labels_train_idx.shape[0]} images with no labels in train set")

# sample that set to the size of 10% of images with labels in train set
n_images_with_labels_train = sampled_df.query("split == 'train'").query("n_bboxes > 0").shape[0]
no_labels_train_idx_left, _ = train_test_split(
    no_labels_train_idx, 
    train_size=int(n_images_with_labels_train * 0.1), 
    random_state=42
)
print(f"Sample {no_labels_train_idx_left.shape[0]} images from that subset")

filtered_idx = (
    sampled_df.index.difference(no_labels_train_idx)  # from all indices remove empty images in train set
    .append(no_labels_train_idx_left)  # from removed images sample 10% and add to the remaining indices
)
print(f"Remains: {filtered_idx.shape[0]}")

Got 152 images with no labels in train set
Sample 4 images from that subset
Remains: 88

#### Create directory with symlinks to images

In [80]:
train_images_dir = (images_splits_dir / "train")
shutil.rmtree(train_images_dir, ignore_errors=True)
train_images_dir.mkdir(exist_ok=True, parents=True)

valid_images_dir = (images_splits_dir / "valid")
shutil.rmtree(valid_images_dir, ignore_errors=True)
valid_images_dir.mkdir(exist_ok=True, parents=True)

src2dest = dict()

df = sampled_df.loc[filtered_idx]

for i, row in df.iterrows():
    src_path = row.path
    image_name = row.image_id
    split = row.split
    
    dest_path = (images_splits_dir / f"{split}/{image_name}.jpg").resolve().as_posix()
    os.symlink(src_path, dest_path)
    src2dest[src_path] = dest_path
    
dest2src = {v:k for k, v in src2dest.items()}

#### Create train/valid/data files

In [81]:
with open(prepared_data_dir / 'train.txt', 'w') as f:
    for path in df.query("split == 'train'").path:
        f.write(src2dest[path] + '\n')
        
with open(prepared_data_dir / 'valid.txt', 'w') as f:
    for path in df.query("split == 'valid'").path:
        f.write(src2dest[path] + '\n')
        
data = dict(
    train = (prepared_data_dir / 'train.txt').resolve().as_posix(),
    val = (prepared_data_dir / 'valid.txt').resolve().as_posix(),
    nc = 1,
    names = ['starfish']
)

with open(prepared_data_dir / 'data.yaml', 'w') as f:
    yaml.dump(data, f, default_flow_style=False)

### Labels

Для каждого изображения, на котором есть хотя бы один объект необходимо сделать файл с расположением этих объектов в формате

```bash
> cat image_id.txt
  obj_id_1 x_1 y_1 width_1 height_1
  obj_id_2 x_2 y_2 width_2 height_2
```

x, y, width, height должны быть указаны в формате YOLO, т.е. в еденицах относительно высоты и ширины

In [82]:
train_labels_dir = prepared_data_dir / "labels/train"
train_labels_dir.mkdir(parents=True, exist_ok=True)

valid_labels_dir = prepared_data_dir / "labels/valid"
valid_labels_dir.mkdir(parents=True, exist_ok=True)

#### Save labels to files

In [83]:
all_boxes = []

for i, row in df.iterrows():
    num_bbox = len(row.bboxes)
    if num_bbox == 0:
        continue
    
    image_name = row.image_id
    image_height = 720
    image_width = 1280
    bboxes_coco = np.array(row.bboxes).astype(np.float32).copy()
    names = ['starfish'] * num_bbox
    labels = [0] * num_bbox
    split = row.split
    
    filename = prepared_data_dir / f"labels/{split}/{image_name}.txt"
    
    with open(filename, 'w') as f:
        bboxes_yolo = coco2yolo(image_height, image_width, bboxes_coco)
        bboxes_yolo = np.clip(bboxes_yolo, 0, 1)
        
        all_boxes.extend(bboxes_yolo)
        
        for bbox_idx in range(len(bboxes_yolo)):
            bb = str(bboxes_yolo[bbox_idx])[1:-1]
            
            annot = str(str(labels[bbox_idx])) + ' ' + bb + '\n'
            annot = ''.join(annot)
            annot = annot.strip('')
            
            f.write(annot)

#### Count files

In [84]:
!echo "Train set:"
!echo "Number of labels in train"
!wc -l {prepared_data_dir / 'train.txt'}
!ls {train_labels_dir} | wc -l

!echo {"-"*50}

!echo "Valid set:"
!wc -l {prepared_data_dir / 'valid.txt'}
!echo "Number of labels in valid"
!ls {valid_labels_dir} | wc -l

!echo {"-"*50}

!echo "data.yaml"
!cat {prepared_data_dir / "data.yaml"}

Train set:
Number of labels in train
50 ../../data/splits/s1/train.txt
46
--------------------------------------------------
Valid set:
38 ../../data/splits/s1/valid.txt
Number of labels in valid
9
--------------------------------------------------
data.yaml
names:
- starfish
nc: 1
train: /home/isabella/code/competitions/great_barrier_reef/data/splits/s1/train.txt
val: /home/isabella/code/competitions/great_barrier_reef/data/splits/s1/valid.txt